spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:mysql://mysql-2787bae0-tongahung-06c5.c.aivencloud.com:23545/defaultdb?sslMode=REQUIRED&serverTimezone=UTC
    username: avnadmin
    password: AVNS_n0IJfNTD1HXSbjGFuC9
#
#    hikari:
#      data-source-properties:
#        sslMode: REQUIRED
#        enabledTLSProtocols: TLSv1.2,TLSv1.3
#    url: jdbc:mysql://localhost:3306/triky
#    username: root
#    password: 0801
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: tongahung@gmail.com
    password: qrbkkgsxfeyimtqr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  default-avatar: http://localhost:8080/uploads/avatars/default-avatar.png
# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0
jwt:
  expiryMinutes: 1
  expiryDay: 5
  accessToken: 4O/FR2P+LGV/GLpMNPqNib1HiAppQg4VgY2xzY7k0OA=
  refreshToken: GcL7IFcXNLhYs5noJgw/smETSFSJYUpaFKu+U1EoCiw=
